{
 "title": "STORY-Testnet-Blockchain Copy",
 "description": "Story Metrics",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS", "label": "Datasource", "query": "prometheus" },
   { "name": "chain_id", "label": "Chain ID", "query": "iliad-0" },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values({chain_id=\"$chain_id\"},instance)"
    }
   },
   {
    "name": "validator",
    "query": "3D43466B8ED649092AE86712F19235201707C782"
   }
  ]
 },
 "panels": [
  {
   "title": "Finalize Block Method Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(cometbft_abci_connection_method_timing_seconds_count{method=\"finalize_block\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Flush Method Histogram",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(cometbft_abci_connection_method_timing_seconds_bucket{method=\"flush\"}[5m])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CometBFT P2P Monitoring",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(cometbft_p2p_message_receive_bytes_total{message_type=\"blocksync_BlockResponse\"}[5m])) by (message_type)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(cometbft_p2p_message_receive_bytes_total{message_type=\"consensus_HasVote\"}[5m])) by (message_type)\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(cometbft_p2p_message_receive_bytes_total[5m])) by (message_type)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Commit Method Timing",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 11, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(cometbft_abci_connection_method_timing_seconds_sum{method=\"commit\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Info Method Execution",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(cometbft_abci_connection_method_timing_seconds_count{method=\"info\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$chain_id overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Block Height",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "cometbft_consensus_latest_block_height{chain_id=\"$chain_id\"}"
      }
     ]
    },
    {
     "title": "Total Transactions",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "cometbft_consensus_total_txs{chain_id=\"$chain_id\"}"
      }
     ]
    },
    {
     "title": "Avg Block Time",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "cometbft_consensus_block_interval_seconds_count{chain_id=\"$chain_id\"}"
      }
     ]
    },
    {
     "title": "Bonded Tokens",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "cometbft_consensus_validator_power{chain_id=\"$chain_id\", validator_address=\"$validator\"}"
      }
     ]
    },
    {
     "title": "Validators",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "cometbft_consensus_validators{chain_id=\"$chain_id\"}",
       "legendFormat": "Active"
      },
      {
       "expr": "cometbft_consensus_missing_validators{chain_id=\"$chain_id\"}",
       "legendFormat": "Missing"
      },
      {
       "expr": "cometbft_consensus_byzantine_validators{chain_id=\"$chain_id\"}",
       "legendFormat": "Byzantine"
      }
     ]
    },
    {
     "title": "Voting Power",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "cometbft_consensus_validators_power{chain_id=\"$chain_id\"}",
       "legendFormat": "Online"
      },
      {
       "expr": "cometbft_consensus_missing_validators_power{chain_id=\"$chain_id\"}",
       "legendFormat": "Missing"
      },
      {
       "expr": "cometbft_consensus_byzantine_validators_power{chain_id=\"$chain_id\"}",
       "legendFormat": "Byzantine"
      }
     ]
    },
    {
     "title": "Block Size",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "cometbft_consensus_block_size_bytes{chain_id=\"$chain_id\"}",
       "legendFormat": "Block Size"
      }
     ]
    },
    {
     "title": "Transactions",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "cometbft_consensus_num_txs{chain_id=\"$chain_id\"}",
       "legendFormat": "Transactions"
      }
     ]
    }
   ]
  },
  {
   "title": "instance overview: $instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "repeat": "instance",
   "targets": [
    {}
   ]
  },
  {
   "title": "Connected Peers",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "cometbft_p2p_peers{chain_id=\"$chain_id\"}"
    }
   ]
  },
  {
   "title": "Unconfirmed Transactions",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "cometbft_mempool_size{chain_id=\"$chain_id\"}"
    }
   ]
  },
  {
   "title": "Failed Transactions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_mempool_failed_txs{chain_id=\"$chain_id\"}"
    }
   ]
  },
  {
   "title": "Recheck Times",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_mempool_recheck_times{chain_id=\"$chain_id\"}"
    }
   ]
  },
  {
   "title": "Total Network Input",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "cometbft_p2p_peer_receive_bytes_total{chain_id=\"$chain_id\"}",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "Total Network Output",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "expr": "cometbft_p2p_peer_send_bytes_total{chain_id=\"$chain_id\"}",
     "legendFormat": "{{peer_id}}"
    }
   ]
  }
 ]
}